### ISSUE TITLE
Indonesian Translation Progress

### ISSUE THREAD

**Issue by gatsbybot** [gatsbyjs/gatsby-id#1]
## For New Translators

To translate a page:

1. Check that no one else has claimed your page in the checklist and comments below.
2. Comment below with the name of the page you would like to translate. **Please take only one page at a time**.
3. Clone this repo, translate your page, and submit a pull request!

Before contributing, read the glossary and style guide to understand how to translate various technical and Gatsby-specific terms.

Please be prompt with your translations! If you find that you can't commit anymore, let the maintainers know so they can assign the page to someone else.

## For Maintainers

When someone volunteers, edit this issue with the username of the volunteer, and with the PR. Ex:

- [ ] Home Page (@gatsbybot) #1

When PRs are merged, make sure to mark that page as completed!

## Core Pages

**These pages should be translated first.** These pages must be translated to be considered an official Gatsby localization.

### Community

* [x] community/code-of-conduct (@hannaiazizah) #20 

### Tutorial

* [x] tutorial/index (@iamyuu) #7
* [x] tutorial/part-zero (@bangunbagustapa) #8 
* [x] tutorial/part-one (@sprabowo) #10 
* [x] tutorial/part-two (@andriawan) #25  
* [x] tutorial/part-three (@herkahahaha) #28  
* [x] tutorial/part-four (@pbwibowo) #40 
* [x] tutorial/part-five (@iamyuu) #27 
* [x] tutorial/part-six (@bangunbagustapa) #41 
* [x] tutorial/part-seven (@andihaki) #34 
* [x] tutorial/part-eight (@herkahahaha) #35 
    
### Docs

* [x] docs/index (@bangunbagustapa) #4 
* [x] docs/quick-start (@bangunbagustapa) #6 
* [ ] docs/glossary (@zweimach) #46 
* [x] docs/add-page-metadata (@cakasuma) #45 
* [ ] docs/add-custom-webpack-config (@cakasuma)
* [x] docs/gatsby-cli (@bangunbagustapa) #26 
    
#### Recipes

* [x] docs/recipes (@wafaulhimam) #42 
* [ ] docs/recipes/pages-layouts
* [ ] docs/recipes/styling-css
* [ ] docs/recipes/working-with-starters
* [ ] docs/recipes/working-with-themes
* [ ] docs/recipes/sourcing-data
* [ ] docs/recipes/querying-data
* [ ] docs/recipes/working-with-images
* [ ] docs/recipes/transforming-data
* [ ] docs/recipes/deploying-your-site

#### API Reference

* [ ] docs/api-reference
* [ ] docs/theme-api
* [ ] docs/gatsby-link
* [ ] docs/gatsby-image
* [ ] docs/gatsby-config
* [ ] docs/browser-apis
* [ ] docs/ssr-apis
* [ ] docs/api-files
* [ ] docs/api-files-gatsby-config
* [ ] docs/api-files-gatsby-browser
* [ ] docs/api-files-gatsby-node
* [ ] docs/api-files-gatsby-ssr
* [ ] docs/actions
* [ ] docs/graphql-api
* [ ] docs/node-apis
* [ ] docs/node-api-helpers
* [ ] docs/node-model
* [ ] docs/node-interface
* [ ] docs/schema-customization
* [ ] docs/api-specification

**Comment by bangun-jds** [comment]
Can i translate docs/index @cendekia @coroo? But it's a little too short, i want to add docs/quick-start as well.

**Comment by cendekia** [comment]
> Can i translate docs/index @cendekia @coroo? But it's a little too short, i want to add docs/quick-start as well.

Yes please 😊

**Comment by bangun-jds** [comment]
Ok forked, thanks 👌

**Comment by iamyuu** [comment]
Can i translate tutorial/index @cendekia @coroo?

**Comment by cendekia** [comment]
> Can i translate tutorial/index @cendekia @coroo?

Silahkan 👌

**Comment by bangun-jds** [comment]
Hi, I finished translating `docs/index` and `docs/quick-start`. Now waiting for review. Can I translate `tutorial/part-zero` next?

**Comment by cendekia** [comment]
> Hi, I finished translating `docs/index` and `docs/quick-start`. Now waiting for review. Can I translate `tutorial/part-zero` next?

Yeah sure, no one claims it yet

**Comment by sprabowo** [comment]
i joined to translate `tutorial/part-one` mas @cendekia

**Comment by cendekia** [comment]
> i joined to translate `tutorial/part-one` mas @cendekia

Yes, please :)

**Comment by andriawan** [comment]
Could i translate tutorial/part-two @cendekia @coroo?

**Comment by coroo** [comment]
> Could i translate tutorial/part-two @cendekia @coroo?

Yes please @andriawan :)

**Comment by bangun-jds** [comment]
I'm working on `docs/gatsby-cli` if no one claims, thank you @cendekia @coroo!

**Comment by herkahahaha** [comment]
mass @cendekia @coroo! ,boleh saya ikutan translate tutorial/part-three yaa

**Comment by cendekia** [comment]
> mass @cendekia @coroo! ,boleh saya ikutan translate tutorial/part-three yaa

Silahkan 👌

**Comment by pbwibowo** [comment]
mas @cendekia @coroo , boleh translate yang tutorial/part-four ?

**Comment by coroo** [comment]
Silahkan @pbwibowo 😉👌

**Comment by iamyuu** [comment]
I want to translate page `tutorial/five` @cendekia @coroo

**Comment by bangun-jds** [comment]
I'm working on `tutorial/part-six` now, thank you @cendekia @coroo.

**Comment by andihaki** [comment]
Hi admin, saya boleh bantu kontribusi di page tutorial/part-seven @cendekia @coroo ?

**Comment by coroo** [comment]
Yes please @andihaki

**Comment by herkahahaha** [comment]
mass @cendekia & @coroo. , saya sambung translate tutorial/part-eight yaa?

**Comment by coroo** [comment]
Yes please @herkahahaha

**Comment by wafaulhimam** [comment]
Hello mas @cendekia & @coroo, can I edit some word in this page?
https://github.com/gatsbyjs/gatsby-id/blob/master/style-guide.md

**Comment by coroo** [comment]
Hi @wafaulhimam . Thank you for your enthusiasm. I already comment in your PR.

**Comment by wafaulhimam** [comment]
thanks, bro @coroo 
May I translate for docs/recipes? @coroo & @cendekia

**Comment by cendekia** [comment]
> thanks, bro @coroo
> May I translate for docs/recipes? @coroo & @cendekia

Go ahead @wafaulhimam, it's already reserved for you

**Comment by zweimach** [comment]
@cendekia, I'm half-way to translate glossary.

**Comment by cendekia** [comment]
> @cendekia, I'm half-way to translate glossary.

Silahkan dilanjutkan :)

**Comment by wafaulhimam** [comment]
thanks, Bro @cendekia

**Comment by pbwibowo** [comment]
Mas saya translate bagian ini docs/docs/add-page-metadata.md boleh ?

**Comment by coroo** [comment]
Silahkan @pbwibowo

**Comment by wafaulhimam** [comment]
Hello mas @coroo & @cendekia, may you check my PR for translate recipes.md, please? Thanks
https://github.com/gatsbyjs/gatsby-id/pull/42

**Comment by cakasuma** [comment]
Hi, I would like to translate this page https://www.gatsbyjs.org/contributing/why-contribute-to-gatsby/ please 🙏

**Comment by cakasuma** [comment]
why-contribute-to-gatsby sudah ketranslate ternyata, saya coba translate add-page-metadata. may you please check my PR here [#45](https://github.com/gatsbyjs/gatsby-id/pull/45), Thank you so much!

**Comment by coroo** [comment]
@cakasuma done. Please check your PR update 😁

**Comment by coroo** [comment]
> Hello mas @coroo & @cendekia, may you check my PR for translate recipes.md, please? Thanks
> #42

Done 😁

**Comment by coroo** [comment]
> @cendekia, I'm half-way to translate glossary.

@zweimach any update on glossary?

**Comment by cakasuma** [comment]
Makasih banyak mas @coroo  . I'd like to continue with docs/add-custom-webpack-config.md

**Comment by wafaulhimam** [comment]
hello mas bro @coroo & @cendekia, may I translate for these: 
- docs/api-files-gatsby-config.md
- docs/api-files-gatsby-browser.md
- docs/api-files-gatsby-node.md
- docs/api-files-gatsby-ssr.md
And wanna ask, Mas, why we are not creating one channel 'localization/translation-id' in GatsbyJS Discord Channel?

Thank you

**Comment by coroo** [comment]
> Makasih banyank mas @coroo . I'd like to continue with docs/add-custom-webpack-config.md

Hi @cakasuma , please let us know if there are any problem regarding docs/add-custom-webpack-config.md . We re still waiting for you 😁

**Comment by jliussuweno** [comment]
Hi Mas @coroo & @cendekia , i want translate 

- docs/adding-forms.md
thank you

**Comment by rikinotnull** [comment]
Hi Mr. @coroo & Mr. @cendekia, can i translate [`docs/contributing/where-to-participate`](https://github.com/gatsbyjs/gatsby-id/blob/master/docs/contributing/where-to-participate.md) ?

**Comment by the-coder-dude** [comment]
@coroo @cendekia  Can I take `docs/contributing/how-to-contribute.md` ? 🙂

**Comment by b0nz** [comment]
Hi @coroo @cendekia, can I translate `/tutorial/using-a-theme.md`?

**Comment by firmanjabar** [comment]
Hallo @coroo and @cendekia, may i translate this one `docs/recipes/deploying-your-site` ?

**Comment by novanauliazami** [comment]
Hi @coroo @cendekia, Could i translate  `docs/recipes/pages-layouts`?

**Comment by rimbaborne** [comment]
ntap

**Comment by ekaone** [comment]
Hallo Mas @coroo @cendekia, can i contribute translation process for docs/recipes/pages-layouts..?, please response, thanks a million

**Comment by syukrie77** [comment]
Halo mas @coroo @cendekia saya boleh ikut berkontribusi ya

**Comment by syukrie77** [comment]
saya mau kontribusi untuk translate di tutorial Plugin & Theme Tutorials ya mas @coroo @cendekia

**Comment by ezralazuardy** [comment]
@tesseralis it's seems this translation progress is no longer maintained, some pull request eg. #49 is not resolved yet since the maintainer of this repo is not active. it would be nice to add a new maintainer (native indonesian) to maintain the quality of this repository. i dont mind to help maintaining this repo tho :).

**Comment by firmanjabar** [comment]
I would love to help too

**Comment by ezralazuardy** [comment]
seems like @gatsbyjs still experiencing some internal issue here.

- https://twitter.com/tesseralis/status/1293649007739191296
- https://gist.github.com/gatsbyjs-employees/5b08b884be088bce54abaf4f980fbf7b#file-open-letter-to-the-gatsby-community-md

i'll keep looking forward into this thread, hopefully this repo (indonesian translation of gatsby docs) can be actively maintained again.

**Comment by vzrenggamani** [comment]
> seems like @gatsbyjs still experiencing some internal issue here.
> 
> * https://twitter.com/tesseralis/status/1293649007739191296
> * https://gist.github.com/gatsbyjs-employees/5b08b884be088bce54abaf4f980fbf7b#file-open-letter-to-the-gatsby-community-md
> 
> i'll keep looking forward into this thread, hopefully this repo (indonesian translation of gatsby docs) can be actively maintained again.

I can see it and looking forward for the TL progress... Hope the issues get resolved soon..

**Comment by vzrenggamani** [comment]
@tesseralis Should we need to sync this repo to the base gatsby js repo?
